name: islam_ansiklopedisi
description: Profesyonel Islam Ansiklopedisi Uygulamasi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# İkon Ayarları
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false             # <--- HATAYI ÇÖZEN KISIM BURASI (True idi False yaptık)
  image_path: "images.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true