name: Final Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Temizlik
        run: flutter clean

      - name: Proje Olustur
        run: flutter create . --platforms android

      # WebView için Android sürüm ayarı (Mecburi)
      - name: SDK Ayari
        run: |
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' android/app/build.gradle

      - name: Paketleri Getir
        run: flutter pub get
      
      # APK Derle
      - name: APK Derle
        run: flutter build apk --debug

      - name: APK Yukle
        uses: actions/upload-artifact@v4
        with:
          name: islam-app-sonuc
          path: build/app/outputs/flutter-apk/app-debug.apk