name: APK Oluşturucu

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4

      - name: Java'yı Kur
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Flutter Kur
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Eksik Proje Dosyalarini Olustur
        run: flutter create . --platforms android

      - name: Paketleri Getir
        run: flutter pub get

      - name: APK Derle
        run: flutter build apk --debug

      - name: APK'yı Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: uygulama-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk